const SET_LIGHT_ON = 'SET_LIGHT_ON'
const SET_SIGNIN_STATE = 'SET_SIGNIN_STATE'
const SET_SIGNIN_USER = 'SET_SIGNIN_USER'
const SET_PERMISSIONS = 'SET_PERMISSIONS'

export {
  SET_LIGHT_ON,
  SET_SIGNIN_STATE,
  SET_SIGNIN_USER,
  SET_PERMISSIONS
}
